// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table benefits [headercolor: #3498DB] {
  id integer [pk, unique]
  vesting_schedule_id integer [not null, ref: - vesting_schedules.id]
  health integer [not null, default: 0]
  retirement integer [not null, default: 0]
  pto integer [not null, default: 0]
  espp_discount integer [not null, default: 0]
  espp_diff integer [not null, default: 0]
  education integer [not null, default: 5250]
  last_updated timestamp [not null, default: `now()`]

  indexes {
    id [unique, name: benefits, type: hash]
  }
}

Table vesting_schedules [headercolor: #3498DB] {
  id integer [pk, unique]
  y1 integer [ default: 0, note: 'Year 1 Vested Percentage' ]
  y2 integer [ default: 0, note: 'Year 2 Vested Percentage' ]
  y3 integer [ default: 0, note: 'Year 3 Vested Percentage' ]
  y4 integer [ default: 0, note: 'Year 4 Vested Percentage' ]
  y5 integer [ default: 0, note: 'Year 5 Vested Percentage' ]
  last_updated timestamp [not null, default: `now()`]

  indexes {
    id [unique, name: vesting_schedules, type: hash]
  }
}

Table company [headercolor: #3498DB] {
  id integer [pk, unique]
  name varchar [not null, unique]
  benefits_id integer [not null, unique, ref: - benefits.id]
  stock_id integer [ref: - stock.id]

  indexes {
    id [unique, name: company, type: hash]
  }
}

Table location [headercolor: #3498DB] {
  id integer [pk, unique]
  name varchar
  street_1 varchar [not null]
  street_2 varchar
  city varchar [not null]
  state char(2) [not null]
  zipcode integer [not null]
  cola_index integer
  last_updated timestamp [not null, default: `now()`]

  indexes {
    id [unique, name: location, type: hash]
  }
}

Table stock [headercolor: #3498DB] {
  id integer [pk, unique]
  ticker varchar [not null, unique]
  market varchar [not null, unique]
  last_close integer [not null]
  last_open integer [not null]
  historical_index_id integer [not null]
  last_updated timestamp [not null, default: `now()`]

  indexes {
    id [unique, name: stock, type: hash]
  }
}

Table stock_history [headercolor: #3498DB] {
  id integer [pk, unique]
  stock_id integer [not null, ref: < stock.id ]
  date varchar [not null]
  high integer [not null]
  low integer [not null]
  open integer [not null]
  close integer [not null]
  created_at timestamp [not null, default: `now()`]

  indexes {
    id [unique, name: stock_history, type: hash]
    (stock_id, date, high) [unique, name: 'daily_high', note: 'Daily KPIs after close', type: hash]
    (stock_id, date, low) [unique, name: 'daily_low', note: 'Daily KPIs after close', type: hash]
  }
}

Table position [headercolor: #3498DB] {
  id integer [pk, unique]
  company_id varchar [not null, ref: < company.id]
  title varchar [not null]
  base integer [not null]
  rsu integer
  performance_bonus integer
  sign_on_bonus integer
  status varchar [not null]
  location_id integer [not null, ref: < location.id]
  created_at timestamp [not null, default: `now()`]

  indexes {
    id [unique, name: position, type: hash]
  }
}
